name: gradution_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.3.0-197.0.dev <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^17.1.2
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_timezone: ^1.0.8
  flutter_tts: ^4.0.1
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: 0.19.0
  mime: ^1.0.5
  numberpicker: ^2.1.2
  page_transition: ^2.1.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  timezone: ^0.9.3
  translator: ^1.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
