class AppString{
  static String appName ='Autism children';
  static String onBoardingTitleOne ='Discovering things ';
  static String onBoardingSubTitleOne =' When you find something you don\'t know you can take a picture to wonder what the thing is ';
  static String onBoardingTitleTwo ='Daily tasks ';
  static String onBoardingSubTitleTwo ='You can upload the picture to identify its contents ';
  static String onBoardingTitleThree ='Parental supervision ';
  static String onBoardingSubTitleThree =' can organize tasks and track the child\'s location ';
  static String onBoardingTitleFour ='Welcome ';
  static String onBoardingSubTitleFour ='Let`s Start! ';
  static String signInWelcome ='Welcome back ! ';
  static String welcome ='Welcome ! ';
  static String signInSubTitle ='Login to your account ';
  static String createAcc ='Create Account ';
  static String forgetPass ='Forget password';
  static String forgetPassSubTitle ='Enter the email address associated with your account';
  static String verification ='Verification ';
  static String verificationSubTitle ='Please enter 4-digit code sent to you at email address ';
  static String newPass ='Create new password ';
  static String newPassSubTitle ='Your new password must be different from previous used password ';
  static String receiveCodeAgain ='Didn’t receive code?  ';
  static String resend ='Resend ';
  static String changeEmail  ='Change Email  ';
  static String changeSuccessfully  ='Password changed successfully! ';
  static String choose  ='Which One Are You?';
  static String child  ='Child';
  static String parent  ='Parent';
  static String next  ='Next';
}